apiVersion: 1

datasources:
  # Loki para logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus_uid
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
    editable: false

  # Prometheus para m√©tricas
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus_uid
    jsonData:
      timeInterval: "15s"
      httpMethod: GET
    editable: false

  # Redis (requiere plugin)
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis:6379
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
    secureJsonData:
      password: trixredis123
    editable: false