apiVersion: v1
kind: Service
metadata:
  name: trix-svm-service
spec:
  selector:
    app: trix-svm-backend
  ports:
  - protocol: TCP
    port: 80 # Puerto externo
    targetPort: 7000 # Puerto de tu aplicaci√≥n
  type: LoadBalancer